services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-bot-app
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
